### ISSUE TITLE
Support extending xarray 

### ISSUE THREAD

**Issue by eyaltrabelsi** [Zsailer/pandas_flavor#13]
I think it can be beneficial to allow to extend xarray (for [example of usecase](https://github.com/ericmjl/pyjanitor/pull/585) )

**Comment by Zsailer** [comment]
Hm, this is a really cool idea. 

I'd be happy to review+accept a PR for this idea. Would you be interested in porting this from pyjanitor?

**Comment by Zsailer** [comment]
@ericmjl @zbarry pinging you for discussion as well.

Now I'm regretting the name `pandas_flavor` 😆

**Comment by eyaltra** [comment]
@Zsailer sure how should i name the file :)

**Comment by Zsailer** [comment]
For now, let's name it `xarray.py` and import the register methods in the `__init__.py`. We may refactor after further discussion.

**Comment by zbarry** [comment]
Yeah this would be great to have in here. It felt weird basically cloning pf's model in a separate package.

> Now I'm regretting the name pandas_flavor laughing

:)

**Comment by zbarry** [comment]
@Zsailer - if it's ok with you, would you mind cutting a release with the xarray addition and update the conda-forge package so I could go ahead and refactor the pyjanitor xarray code to depend on it?

**Comment by Zsailer** [comment]
@zbarry, I've released v0.2.0 with xarray support. It's available on PyPI now. I'm updating the conda-forge package—you can watch the progress [here](https://github.com/conda-forge/pandas_flavor-feedstock/pull/2).

**Comment by Zsailer** [comment]
@zbarry, I've released v0.2.0 with xarray support. It's available on PyPI now. I'm updating the conda-forge package—you can watch the progress [here](https://github.com/conda-forge/pandas_flavor-feedstock/pull/2).

**Comment by zbarry** [comment]
@Zsailer - Appreciate it!

**Comment by Zsailer** [comment]
Closing, since this was merged in #15! Thanks, @eyaltrabelsi!

**Comment by zbarry** [comment]
Thanks again, both.

**Comment by SethMMorton** [comment]
It seems that `pandas_flavor` now requires `xarray` to be installed now, even if I choose not to use `xarray`. Perhaps this should have been an optional dependency?
