### ISSUE TITLE
different scikit-bio dependencies

### ISSUE THREAD

**Issue by CodingForester** [Zsailer/pandas_flavor#2]
Hi, I ran into the issue:

phylotoast 1.4.0rc2 has requirement scikit-bio<=0.4.2, but you'll have scikit-bio 0.5.1 which is incompatible.
gneiss 0.4.2 has requirement scikit-bio==0.5.1, but you'll have scikit-bio 0.4.2 which is incompatible.

Either way I cant install both versions, because pip overwrites the other. Even having an environment would not solve that I guess. How can you deal with that? 

Cheers,
Robert

**Comment by CodingForester** [comment]
Solved it with conda install scikit-bio==0.4.2.

**Comment by Zsailer** [comment]
@AmbrosiaFungus are you using *pandas_flavor* with these tools? 

Pandas_flavor does not depend on scikit-bio, so it shouldn't play any role in determining which scikit-bio package is installed. 

Did you experience a problem with pandas_flavor?

**Comment by CodingForester** [comment]
`pip install pandas_flavor`
Requirement already satisfied: pandas_flavor in ./anaconda3/lib/python3.5/site-packages (0.1.1)
Requirement already satisfied: pandas in ./anaconda3/lib/python3.5/site-packages (from pandas_flavor) (0.20.1)
Requirement already satisfied: python-dateutil>=2 in ./anaconda3/lib/python3.5/site-packages (from pandas->pandas_flavor) (2.6.1)
Requirement already satisfied: pytz>=2011k in ./anaconda3/lib/python3.5/site-packages (from pandas->pandas_flavor) (2018.3)
Requirement already satisfied: numpy>=1.7.0 in ./anaconda3/lib/python3.5/site-packages (from pandas->pandas_flavor) (1.12.1)
Requirement already satisfied: six>=1.5 in ./anaconda3/lib/python3.5/site-packages (from python-dateutil>=2->pandas->pandas_flavor) (1.11.0)
**phylotoast 1.4.0rc2 has requirement scikit-bio<=0.4.2, but you'll have scikit-bio 0.5.1 which is incompatible.**


I wanted to use phylopandas and run into the above issues. Don't know why, but I got it to work in the end.

**Comment by Zsailer** [comment]
Ah I see! Well, thank you for your interest in phylopandas 😄 If you run into more issues, feel free to hop on this [gitter channel](https://gitter.im/phylopandas/Lobby) for help.

Thinking about the issue above,

*I think* anaconda throws a warning about dependency conflicts that already exist, no matter what you're trying to install... So, even though phylopandas doesn't use scikit-bio, anaconda recognized there was a dependency conflict from previous `pip` calls and wanted to remind you to fix it.

**Comment by Zsailer** [comment]
Closing this issue since it's gone stale. Feel free to reopen if you're still having issues.
