### ISSUE TITLE
lazy-loader causes ERROR when installing version 0.3.0

### ISSUE THREAD

**Issue by solita-vilmaja** [Zsailer/pandas_flavor#22]
When I run `pip install pandas-flavor==0.3.0`, I get the following error

ERROR: Could not find a version that satisfies the requirement lazy-loader==0.1rc2 (from pandas-flavor)

**Comment by samukweku** [comment]
@solita-vilmaja apologies for the late response. Lazy loading has been removed. Thanks for the feedback
