### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ericmjl** [Zsailer/pandas_flavor#5]
Hey @Zsailer, please let me know if you'd like help doing a release to PyPI -- I've got tests failing on the latest pyjanitor PR ([here](https://github.com/ericmjl/pyjanitor/pull/22)) but only because I'm relying on the latest code in PR #4!

**Comment by Zsailer** [comment]
I was actually just about to push a new version! 

Version 0.1.2 should be live now.

**Comment by ericmjl** [comment]
WOOHOO!!! Thanks a ton!! :smile:
