### ISSUE TITLE
conda-forge recipe

### ISSUE THREAD

**Issue by ericmjl** [Zsailer/pandas_flavor#6]
Hey @Zsailer,

I'd like to put this up on conda-forge. Do you plan on putting a license in the repository?

**Comment by Zsailer** [comment]
That would be awesome! #7 adds the MIT license. 

Sorry that this package is so under-developed! I didn't think anyone would be interested 😆. 

That said, if you have ideas for making the README more clear, feel free to change it too!

**Comment by Zsailer** [comment]
Also, would you like to be added as collaborator to this project?

**Comment by ericmjl** [comment]
Sure, happy to do so :smile: Also gonna add you on the conda-forge recipe as a maintainer (don't worry, with the bot, it's now mostly merging after seeing that tests pass; I'll race you to the merge!).

**Comment by ericmjl** [comment]
Has been done, by @ocefpaf! https://github.com/conda-forge/staged-recipes/pull/6301
